@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.constructscasting.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;