@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.constructscasting.compat.metalborn;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;