@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.constructscasting.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;