@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.constructscasting.materials;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;