@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.snackpirate.constructscasting.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;